# This workflow deploys a Resource Group and Storage Account Table
# for the Poorman IPAM solution

name: Deploy-Storage-Account

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allows you to run this workflow from a starter workflow
  workflow_call:
    inputs:
      RESOURCEGROUPNAME:
        required: true
        type: string
      SUBSCRIPTIONID:
        required: true
        type: string
      REGION:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
    outputs:
      ResourceGroupName:
        description: "Name of the resource group"
        value: ${{ jobs.build-and-deploy.outputs.ResourceGroupName }}
      StorageAccountName:
        description: "Name of the storage account generated in arm template"
        value: ${{ jobs.build-and-deploy.outputs.StorageAccountName }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest    
    
    outputs:
      ResourceGroupName: ${{ steps.output.outputs.ResourceGroupName }}
      StorageAccountName: ${{ steps.output.outputs.StorageAccountName }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - run: |
          echo "${{ inputs.RESOURCEGROUPNAME }}"
          echo "${{ inputs.SUBSCRIPTIONID }}"
          echo "${{ inputs.REGION }}"
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Deploy Azure Resource Group
      - name: Azure CLI Action
        uses: Azure/cli@1.0.4
        with:
          # Specify the script here
          inlineScript: |
            az group create --name ${{ inputs.RESOURCEGROUPNAME }} --location ${{ inputs.REGION }}
      # Deploy Storage Account
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        id: deploy-storage-account
        with:
          scope: resourcegroup
          subscriptionId: ${{ inputs.SUBSCRIPTIONID }}
          region: ${{ inputs.REGION }}
          resourceGroupName: ${{ inputs.RESOURCEGROUPNAME }}
          template: src/templates/azuredeploy.json          
          deploymentMode: incremental
          deploymentName: "AIPAS-storageaccount"
          parameters: src/templates/azuredeploy.parameters.json
      # Output Storage Account ResourceGroup Name and Storage Account Name
      - run: |
          echo ${{ steps.deploy-storage-account.outputs.ResourceGroupName }}
          echo "::set-output name=ResourceGroupName::${{ steps.deploy-storage-account.outputs.ResourceGroupName }}"
          echo ${{ steps.deploy-storage-account.outputs.StorageAccountName }}
          echo "::set-output name=StorageAccountName::${{ steps.deploy-storage-account.outputs.StorageAccountName }}"
        id: output
