name: Deploy to all Environments

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ none ]
  # pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-storage-account:
    uses: .github/workflows/deploy-storageaccount-reusable.yaml@svs3deployment
    with:
      RESOURCEGROUPNAME: "rg-aipas-svs3"
      SUBSCRIPTIONID: "8e65589a-9d2b-4d0d-a110-33a515a7f266"
      REGION: "westeurope" 
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  deploy-azure-function:
    needs: deploy-storage-account
    uses: .github/workflows/deploy-azure-function-reusable.yaml@svs3deployment
    with:
      AZURE_FUNCTIONAPP_NAME: "svs3-aipas"
      RESOURCEGROUPNAME: ${{needs.deploy-storage-account.outputs.ResourceGroupName}}
      SUBSCRIPTIONID: "8e65589a-9d2b-4d0d-a110-33a515a7f266"
      STORAGEACCOUNTNAME: ${{needs.deploy-storage-account.outputs.StorageAccountName}}
      REGION: "westeurope" 
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      APP_SETTINGS: ${{ secrets.APP_SETTINGS }}